// <auto-generated />
using Libertas.Discord.Adventure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libertas.Discord.Adventure.Data.Migrations
{
    [DbContext(typeof(AdventureContext))]
    [Migration("20260105011014_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Libertas.Discord.Adventure.Data.Entities.MobPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttackPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAttackPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MobPreset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 32,
                            MinAttackPower = 6,
                            MinHealth = 17,
                            Name = "Abyssal Demon"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/01/21/06/04/dragon-3095910_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 77,
                            MinAttackPower = 6,
                            MinHealth = 62,
                            Name = "Abyssal Drake"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://vignette.wikia.nocookie.net/fairytailfanon/images/8/83/Beltazlel_HS.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 56,
                            MinAttackPower = 6,
                            MinHealth = 41,
                            Name = "Aether Dragon"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/22/11/02/fairy-2164638_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 34,
                            MinAttackPower = 3,
                            MinHealth = 19,
                            Name = "Aether Faerie"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/18/21/10/wolf-1836875_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 30,
                            MinAttackPower = 6,
                            MinHealth = 15,
                            Name = "Aether Wolf"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/07/18/49/priestess-1722370_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 49,
                            MinAttackPower = 2,
                            MinHealth = 34,
                            Name = "Air Elemental"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/05/26/21/32/control-785555_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 47,
                            MinAttackPower = 2,
                            MinHealth = 32,
                            Name = "Ancient Earth Spirit"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/04/13/01/53/man-4123703_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 51,
                            MinAttackPower = 3,
                            MinHealth = 36,
                            Name = "Ancient Spellcaster"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/08/20/12/tree-2127699_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 45,
                            MinAttackPower = 2,
                            MinHealth = 30,
                            Name = "Ancient Tree Spirit"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/04/16/21/49/deer-1333814_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 22,
                            MinAttackPower = 3,
                            MinHealth = 7,
                            Name = "Arcane Construct"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/22/21/44/mask-1409287_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 31,
                            MinAttackPower = 3,
                            MinHealth = 16,
                            Name = "Arcane-Touched Satyr"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/06/21/08/fantasy-2824654_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 36,
                            MinAttackPower = 3,
                            MinHealth = 21,
                            Name = "Arcane-Touched Spriggan"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/03/31/21/41/assassin-1296592_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 11,
                            MinAttackPower = 2,
                            MinHealth = 1,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/14/Durin%27s_Bane.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 22,
                            MinAttackPower = 6,
                            MinHealth = 7,
                            Name = "Balrog"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/10/24/burglar-157142_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 14,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Bandit"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/11/05/09/03/owl-517497_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 15,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Barred Owl"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/70/Wenceslas_Hollar_-_The_basilisk_and_the_weasel.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 62,
                            MinAttackPower = 6,
                            MinHealth = 47,
                            Name = "Basilisk"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://live.staticflickr.com/3741/9187712502_bbecd929e1_b.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 11,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Bat"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/03/27/18/10/bear-1283347_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 24,
                            MinAttackPower = 6,
                            MinHealth = 9,
                            Name = "Bear"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://kagesatsuki.files.wordpress.com/2017/05/170531_02.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 54,
                            MinAttackPower = 6,
                            MinHealth = 39,
                            Name = "Black Wyrm"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/20/16/43/dragon-2662375_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 64,
                            MinAttackPower = 6,
                            MinHealth = 49,
                            Name = "Blood Wyrm"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://i.imgur.com/dxEjIsT.jpg",
                            MaxAttackPower = 15,
                            MaxHealth = 70,
                            MinAttackPower = 8,
                            MinHealth = 55,
                            Name = "Bloodrage Drake"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/02/13/11/57/wolf-635063_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 17,
                            MinAttackPower = 6,
                            MinHealth = 2,
                            Name = "Bloodtooth Wolf"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://www.goodfreephotos.com/cache/art-and-illustrations/hand-coming-up-from-the-swamp_800.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 29,
                            MinAttackPower = 3,
                            MinHealth = 14,
                            Name = "Bog Beast"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/13/07/57/dragon-1976596_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 55,
                            MinAttackPower = 6,
                            MinHealth = 40,
                            Name = "Bronze Dragon"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/10/27/14/17/demon-201422_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 35,
                            MinAttackPower = 3,
                            MinHealth = 20,
                            Name = "Bronze Guardian"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7b/Dragon-Linda_BlackWin24_Jansson.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 68,
                            MinAttackPower = 6,
                            MinHealth = 53,
                            Name = "Bronze Wyrm"
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/12/01/19/35/portrait-1072696_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 16,
                            MinAttackPower = 3,
                            MinHealth = 1,
                            Name = "Brown Eagle"
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/06/01/10/53/face-793186_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 39,
                            MinAttackPower = 3,
                            MinHealth = 24,
                            Name = "Carved Totem"
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/25/16/54/african-lion-2888519_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 31,
                            MinAttackPower = 6,
                            MinHealth = 16,
                            Name = "Cave Lion"
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/07/22/21/29/color-rat-399706_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 9,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Cave Rat"
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/03/13/54/unicorn-2035174_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 35,
                            MinAttackPower = 3,
                            MinHealth = 20,
                            Name = "Celestial Unicorn"
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "https://i.imgur.com/BbBmEOF.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 90,
                            MinAttackPower = 6,
                            MinHealth = 75,
                            Name = "Celestial Wyrm"
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/02/17/09/23/fantasy-3159483_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 24,
                            MinAttackPower = 3,
                            MinHealth = 9,
                            Name = "Centaur Archwizard"
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/12/16/centaur-159538_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 46,
                            MinAttackPower = 3,
                            MinHealth = 31,
                            Name = "Centaur Mage"
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/12/16/centaur-159538_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 21,
                            MinAttackPower = 2,
                            MinHealth = 6,
                            Name = "Centaur Spirit-talker"
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "https://s0.geograph.org.uk/geophotos/04/91/10/4911075_244f2d29.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 42,
                            MinAttackPower = 6,
                            MinHealth = 27,
                            Name = "Charmed Wyrm Statue"
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/14/19/45/dryad-1392438_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 40,
                            MinAttackPower = 3,
                            MinHealth = 25,
                            Name = "Corrupted Dryad"
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/06/06/21/28/phoenix-1440452_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 37,
                            MinAttackPower = 3,
                            MinHealth = 22,
                            Name = "Corrupted Phoenix"
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/04/02/04/53/colorful-1302152_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 42,
                            MinAttackPower = 3,
                            MinHealth = 27,
                            Name = "Corrupted Unicorn"
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "https://i.imgur.com/4HWOp15.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 77,
                            MinAttackPower = 6,
                            MinHealth = 62,
                            Name = "Crystal Drake"
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/09/21/08/14/fantasy-2771073_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 31,
                            MinAttackPower = 3,
                            MinHealth = 16,
                            Name = "Cultist Lord"
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/08/03/10/15/tail-1566250_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 49,
                            MinAttackPower = 3,
                            MinHealth = 34,
                            Name = "Cursed Tentacle"
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/12/16/centaur-159538_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 21,
                            MinAttackPower = 3,
                            MinHealth = 6,
                            Name = "Dappled Centaur"
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/03/16/21/24/fantasy-3232570_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 24,
                            MinAttackPower = 2,
                            MinHealth = 9,
                            Name = "Deer Spirit"
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/14/12/32/forest-1669338_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 23,
                            MinAttackPower = 3,
                            MinHealth = 8,
                            Name = "Doomsayer Cultist"
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/14/19/45/dryad-1392438_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 20,
                            MinAttackPower = 3,
                            MinHealth = 5,
                            Name = "Dryad Spellcaster"
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/19/13/42/eagle-1753002_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 10,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Eagle"
                        },
                        new
                        {
                            Id = 49,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/13/23/08/dragon-2638881_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 80,
                            MinAttackPower = 6,
                            MinHealth = 65,
                            Name = "Earth Dragon"
                        },
                        new
                        {
                            Id = 50,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/09/08/20/54/elephant-4461911_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 48,
                            MinAttackPower = 2,
                            MinHealth = 33,
                            Name = "Earth Elemental"
                        },
                        new
                        {
                            Id = 51,
                            ImageUrl = "https://vignette.wikia.nocookie.net/monster/images/6/6e/DragonRed.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 63,
                            MinAttackPower = 6,
                            MinHealth = 48,
                            Name = "Elder Dragon"
                        },
                        new
                        {
                            Id = 52,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/19/11/31/horror-2156302_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 39,
                            MinAttackPower = 2,
                            MinHealth = 24,
                            Name = "Elder Forest Spirit"
                        },
                        new
                        {
                            Id = 53,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/07/22/12/05/green-man-3554439_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 29,
                            MinAttackPower = 3,
                            MinHealth = 14,
                            Name = "Elder Treant"
                        },
                        new
                        {
                            Id = 54,
                            ImageUrl = "https://i.imgur.com/cZZ6RJh.png",
                            MaxAttackPower = 13,
                            MaxHealth = 61,
                            MinAttackPower = 6,
                            MinHealth = 46,
                            Name = "Emerald Drake"
                        },
                        new
                        {
                            Id = 55,
                            ImageUrl = "https://i.imgur.com/So3u7Ni.png",
                            MaxAttackPower = 10,
                            MaxHealth = 52,
                            MinAttackPower = 3,
                            MinHealth = 37,
                            Name = "Emerald Oracle"
                        },
                        new
                        {
                            Id = 56,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/08/05/00/10/dragon-1571287_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 56,
                            MinAttackPower = 6,
                            MinHealth = 41,
                            Name = "Emerald Wyrm"
                        },
                        new
                        {
                            Id = 57,
                            ImageUrl = "https://i.imgur.com/rCHhnqt.jpg",
                            MaxAttackPower = 15,
                            MaxHealth = 73,
                            MinAttackPower = 8,
                            MinHealth = 58,
                            Name = "Enraged Drake"
                        },
                        new
                        {
                            Id = 58,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/10/23/13/oracle-girl-2133976_960_720.jpg",
                            MaxAttackPower = 12,
                            MaxHealth = 53,
                            MinAttackPower = 5,
                            MinHealth = 38,
                            Name = "Enraged Oracle"
                        },
                        new
                        {
                            Id = 59,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/05/17/18/49/pentecost-3409407_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 61,
                            MinAttackPower = 2,
                            MinHealth = 46,
                            Name = "Ethereal Bird Spirit"
                        },
                        new
                        {
                            Id = 60,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/03/09/07/45/lion-283639_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 61,
                            MinAttackPower = 2,
                            MinHealth = 46,
                            Name = "Ethereal Cat Spirit"
                        },
                        new
                        {
                            Id = 61,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/07/31/17/38/wolf-2559374_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 61,
                            MinAttackPower = 6,
                            MinHealth = 46,
                            Name = "Ethereal Wolf Spirit"
                        },
                        new
                        {
                            Id = 62,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/26/23/41/fairy-2101714_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 39,
                            MinAttackPower = 3,
                            MinHealth = 24,
                            Name = "Faerie"
                        },
                        new
                        {
                            Id = 63,
                            ImageUrl = "https://banner2.kisspng.com/20180205/vjq/kisspng-demon-idea-demon-png-transparent-5a790f727e5a00.3066432715178832505175.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 37,
                            MinAttackPower = 3,
                            MinHealth = 22,
                            Name = "Fel-Corrupted Satyr"
                        },
                        new
                        {
                            Id = 64,
                            ImageUrl = "https://live.staticflickr.com/3156/2806388133_4332cc63b1_z.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 70,
                            MinAttackPower = 6,
                            MinHealth = 55,
                            Name = "Fire Dragon"
                        },
                        new
                        {
                            Id = 65,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/04/16/21/32/flame-726268_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 47,
                            MinAttackPower = 2,
                            MinHealth = 32,
                            Name = "Fire Elemental"
                        },
                        new
                        {
                            Id = 66,
                            ImageUrl = "https://www.maxpixel.net/static/photo/1x/Fee-Magic-Mystical-Fantasy-Fire-Surreal-Elf-3350952.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 38,
                            MinAttackPower = 3,
                            MinHealth = 23,
                            Name = "Fire Fairy"
                        },
                        new
                        {
                            Id = 67,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/09/35/eagle-155747_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 22,
                            MinAttackPower = 3,
                            MinHealth = 7,
                            Name = "Fire Hawk"
                        },
                        new
                        {
                            Id = 68,
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/08/18/14/00/fire-salamander-54533_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 36,
                            MinAttackPower = 3,
                            MinHealth = 21,
                            Name = "Fire Salamander"
                        },
                        new
                        {
                            Id = 69,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/03/16/21/24/fantasy-3232570_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 27,
                            MinAttackPower = 2,
                            MinHealth = 12,
                            Name = "Fire Spirit"
                        },
                        new
                        {
                            Id = 70,
                            ImageUrl = "https://i.imgur.com/x8RIYvo.jpeg",
                            MaxAttackPower = 13,
                            MaxHealth = 52,
                            MinAttackPower = 6,
                            MinHealth = 37,
                            Name = "Fire Wyvern"
                        },
                        new
                        {
                            Id = 71,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/01/27/05/11/cougar-6971086_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 19,
                            MinAttackPower = 3,
                            MinHealth = 4,
                            Name = "Flatland Cougar"
                        },
                        new
                        {
                            Id = 72,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/13/14/15/fantasy-2847724_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 44,
                            MinAttackPower = 3,
                            MinHealth = 29,
                            Name = "Fog Beast"
                        },
                        new
                        {
                            Id = 73,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/22/18/30/anxiety-2878767_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 44,
                            MinAttackPower = 3,
                            MinHealth = 29,
                            Name = "Fog Beast Minion"
                        },
                        new
                        {
                            Id = 74,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/06/19/20/fantasy-2824304_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 28,
                            MinAttackPower = 3,
                            MinHealth = 13,
                            Name = "Forest Atronach"
                        },
                        new
                        {
                            Id = 75,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/06/08/17/23/dragon-3462724_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 79,
                            MinAttackPower = 6,
                            MinHealth = 64,
                            Name = "Forest Drake"
                        },
                        new
                        {
                            Id = 76,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/03/16/15/56/woman-1261048_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 17,
                            MinAttackPower = 3,
                            MinHealth = 2,
                            Name = "Forest Fairie"
                        },
                        new
                        {
                            Id = 77,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/06/10/22/58/composing-2391033_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 19,
                            MinAttackPower = 3,
                            MinHealth = 4,
                            Name = "Forest Guardian"
                        },
                        new
                        {
                            Id = 78,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/02/12/14/01/horse-3148414_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 38,
                            MinAttackPower = 3,
                            MinHealth = 23,
                            Name = "Forest Kirin"
                        },
                        new
                        {
                            Id = 79,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/29/10/44/magician-3047235_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 38,
                            MinAttackPower = 2,
                            MinHealth = 23,
                            Name = "Forest Spirit"
                        },
                        new
                        {
                            Id = 80,
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/02/28/15/47/swirls-18530_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 16,
                            MinAttackPower = 3,
                            MinHealth = 1,
                            Name = "Forest Sprite"
                        },
                        new
                        {
                            Id = 81,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/07/20/00/00/ork-2520855_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 42,
                            MinAttackPower = 6,
                            MinHealth = 27,
                            Name = "Forest Troll"
                        },
                        new
                        {
                            Id = 82,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/25/00/50/third-eye-2886688_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 50,
                            MinAttackPower = 3,
                            MinHealth = 35,
                            Name = "Forest Witch"
                        },
                        new
                        {
                            Id = 83,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/04/24/19/42/fuchs-2257543_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 22,
                            MinAttackPower = 2,
                            MinHealth = 7,
                            Name = "Fox Spirit"
                        },
                        new
                        {
                            Id = 84,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/06/19/15/soap-bubble-1958650_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 48,
                            MinAttackPower = 2,
                            MinHealth = 33,
                            Name = "Frost Elemental"
                        },
                        new
                        {
                            Id = 85,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/12/09/11/16/web-spider-1894655_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 10,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Frost Spider"
                        },
                        new
                        {
                            Id = 86,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/10/13/29/creature-1969074_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 41,
                            MinAttackPower = 6,
                            MinHealth = 26,
                            Name = "Frost Troll"
                        },
                        new
                        {
                            Id = 87,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/28/12/21/giant-eagle-2689367_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 16,
                            MinAttackPower = 3,
                            MinHealth = 1,
                            Name = "Giant Eagle"
                        },
                        new
                        {
                            Id = 88,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/06/20/08/eagle-2044134_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 28,
                            MinAttackPower = 3,
                            MinHealth = 13,
                            Name = "Giant Roc"
                        },
                        new
                        {
                            Id = 89,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2f/DnD_Gnoll.png",
                            MaxAttackPower = 9,
                            MaxHealth = 9,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Gnoll"
                        },
                        new
                        {
                            Id = 90,
                            ImageUrl = "https://i.imgur.com/k5BWr2K.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 84,
                            MinAttackPower = 3,
                            MinHealth = 69,
                            Name = "Golden Amphitere"
                        },
                        new
                        {
                            Id = 91,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/05/18/22/52/dragon-3412281_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 53,
                            MinAttackPower = 3,
                            MinHealth = 38,
                            Name = "Golden Draconid"
                        },
                        new
                        {
                            Id = 92,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/01/05/01/19/dragon-238931_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 66,
                            MinAttackPower = 6,
                            MinHealth = 51,
                            Name = "Golden Dragon"
                        },
                        new
                        {
                            Id = 93,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/10/19/05/21/sculpture-197772_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 100,
                            MinAttackPower = 6,
                            MinHealth = 89,
                            Name = "Golden Guardian Wyrm"
                        },
                        new
                        {
                            Id = 94,
                            ImageUrl = "https://i.imgur.com/zOd2s9R.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 59,
                            MinAttackPower = 6,
                            MinHealth = 44,
                            Name = "Golden Wyrm"
                        },
                        new
                        {
                            Id = 95,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/04/25/21/30/wild-goose-2260866_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 15,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Goose"
                        },
                        new
                        {
                            Id = 96,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/04/12/09/13/fantasy-4121663_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 41,
                            MinAttackPower = 3,
                            MinHealth = 26,
                            Name = "Guardian Statue"
                        },
                        new
                        {
                            Id = 97,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/07/10/22/17/harpy-2491774_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 35,
                            MinAttackPower = 3,
                            MinHealth = 20,
                            Name = "Harpy Matriarch"
                        },
                        new
                        {
                            Id = 98,
                            ImageUrl = "https://www.maxpixel.net/static/photo/1x/Bird-Zoo-Harpy-Berlin-2772092.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 32,
                            MinAttackPower = 3,
                            MinHealth = 17,
                            Name = "Harpy Windsinger"
                        },
                        new
                        {
                            Id = 99,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/01/31/18/44/harpie-618781_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 20,
                            MinAttackPower = 3,
                            MinHealth = 5,
                            Name = "Harpy Witch"
                        },
                        new
                        {
                            Id = 100,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/12/25/16/53/spirit-579807_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 43,
                            MinAttackPower = 2,
                            MinHealth = 28,
                            Name = "Horse Spirit"
                        },
                        new
                        {
                            Id = 101,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/08/19/23/27/dragon-4417431_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 56,
                            MinAttackPower = 6,
                            MinHealth = 41,
                            Name = "Ice Dragon"
                        },
                        new
                        {
                            Id = 102,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/11/07/00/07/fantasy-2925250_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 48,
                            MinAttackPower = 2,
                            MinHealth = 33,
                            Name = "Ice Elemental"
                        },
                        new
                        {
                            Id = 103,
                            ImageUrl = "https://gourmetpapermache.files.wordpress.com/2018/10/1a.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 54,
                            MinAttackPower = 6,
                            MinHealth = 39,
                            Name = "Ice Wyvern"
                        },
                        new
                        {
                            Id = 104,
                            ImageUrl = "https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/361/234/315/636252778560366227.jpeg",
                            MaxAttackPower = 9,
                            MaxHealth = 7,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Imp"
                        },
                        new
                        {
                            Id = 105,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Incubus.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 38,
                            MinAttackPower = 3,
                            MinHealth = 23,
                            Name = "Incubus"
                        },
                        new
                        {
                            Id = 106,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/25/22/55/dragon-1770252_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 70,
                            MinAttackPower = 6,
                            MinHealth = 55,
                            Name = "Jade Drake"
                        },
                        new
                        {
                            Id = 107,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/09/07/04/02/jaguar-2723827_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 28,
                            MinAttackPower = 3,
                            MinHealth = 13,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 108,
                            ImageUrl = "https://vignette.wikia.nocookie.net/forgottenrealms/images/f/f3/Monster_Manual_5e_-_Kobold_-_p195.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 9,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Kobold"
                        },
                        new
                        {
                            Id = 109,
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/11/28/09/46/lava-67574_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 49,
                            MinAttackPower = 2,
                            MinHealth = 34,
                            Name = "Lava Spirit"
                        },
                        new
                        {
                            Id = 110,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/09/20/23/44/hell-454463_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 40,
                            MinAttackPower = 3,
                            MinHealth = 25,
                            Name = "Lesser Felguard"
                        },
                        new
                        {
                            Id = 111,
                            ImageUrl = "https://wallpapercave.com/wp/wp1968832.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 62,
                            MinAttackPower = 6,
                            MinHealth = 47,
                            Name = "Lightning Dragon"
                        },
                        new
                        {
                            Id = 112,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/01/06/03/38/wolf-3916379_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 11,
                            MinAttackPower = 6,
                            MinHealth = 1,
                            Name = "Lone Wolf"
                        },
                        new
                        {
                            Id = 113,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/07/30/09/00/arc-405098_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 39,
                            MinAttackPower = 3,
                            MinHealth = 24,
                            Name = "Magma Giant"
                        },
                        new
                        {
                            Id = 114,
                            ImageUrl = "https://i.imgur.com/k3fQO6t.png",
                            MaxAttackPower = 13,
                            MaxHealth = 51,
                            MinAttackPower = 6,
                            MinHealth = 36,
                            Name = "Minotaur"
                        },
                        new
                        {
                            Id = 115,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/03/17/11/minotaur-1950012_960_720.png",
                            MaxAttackPower = 15,
                            MaxHealth = 61,
                            MinAttackPower = 8,
                            MinHealth = 46,
                            Name = "Minotaur Berserker"
                        },
                        new
                        {
                            Id = 116,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/14/11/21/fantasy-1739989_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 22,
                            MinAttackPower = 6,
                            MinHealth = 7,
                            Name = "Mountain Troll"
                        },
                        new
                        {
                            Id = 117,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/01/20/54/mouse-1708347_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 6,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 118,
                            ImageUrl = "https://i.imgur.com/Y3fFqUX.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 56,
                            MinAttackPower = 6,
                            MinHealth = 41,
                            Name = "Nether Dragon"
                        },
                        new
                        {
                            Id = 119,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/02/28/11/35/dragons-653439_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 66,
                            MinAttackPower = 6,
                            MinHealth = 51,
                            Name = "Night Dragon"
                        },
                        new
                        {
                            Id = 120,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/06/08/39/dragon-3001238_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 57,
                            MinAttackPower = 6,
                            MinHealth = 42,
                            Name = "Obsidian Drake"
                        },
                        new
                        {
                            Id = 121,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/08/05/13/acid-1807514_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 53,
                            MinAttackPower = 2,
                            MinHealth = 38,
                            Name = "Obsidian Vapor Spirit"
                        },
                        new
                        {
                            Id = 122,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/07/17/15/10/ogre-1524018_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 18,
                            MinAttackPower = 6,
                            MinHealth = 3,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = 123,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/04/01/10/30/armour-1299911_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 18,
                            MinAttackPower = 6,
                            MinHealth = 3,
                            Name = "Ogre Bruiser"
                        },
                        new
                        {
                            Id = 124,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Savage_Orc_by_farmerownia.jpg/220px-Savage_Orc_by_farmerownia.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 12,
                            MinAttackPower = 6,
                            MinHealth = 0,
                            Name = "Orc Peon"
                        },
                        new
                        {
                            Id = 125,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/17/20/14/troll-3328592_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 35,
                            MinAttackPower = 6,
                            MinHealth = 20,
                            Name = "Orc Shieldbreaker"
                        },
                        new
                        {
                            Id = 126,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/07/23/19/vintage-1722810_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 18,
                            MinAttackPower = 6,
                            MinHealth = 3,
                            Name = "Orc Slavedriver"
                        },
                        new
                        {
                            Id = 127,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/05/19/10/speule-3000150_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 26,
                            MinAttackPower = 2,
                            MinHealth = 11,
                            Name = "Owlspider"
                        },
                        new
                        {
                            Id = 128,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/18/16/08/wolf-2864647_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 55,
                            MinAttackPower = 3,
                            MinHealth = 40,
                            Name = "Pack of Frost Wolves"
                        },
                        new
                        {
                            Id = 129,
                            ImageUrl = "https://www.nps.gov/whsa/learn/nature/images/Saber_Tooth.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 51,
                            MinAttackPower = 3,
                            MinHealth = 36,
                            Name = "Pack of Sabre Cats"
                        },
                        new
                        {
                            Id = 130,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/08/25/20/59/timber-wolves-907680_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 44,
                            MinAttackPower = 3,
                            MinHealth = 29,
                            Name = "Pack of Wolves"
                        },
                        new
                        {
                            Id = 131,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/25/12/53/peacock-2887882_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 43,
                            MinAttackPower = 2,
                            MinHealth = 28,
                            Name = "Peacock Spirit"
                        },
                        new
                        {
                            Id = 132,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/10/24/burglar-157142_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 8,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Petty Thief"
                        },
                        new
                        {
                            Id = 133,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/03/11/16/38/hirsch-3217239_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 15,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Plagued Deer"
                        },
                        new
                        {
                            Id = 134,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/02/10/22/55/sword-3144759_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 21,
                            MinAttackPower = 3,
                            MinHealth = 6,
                            Name = "Possessed Sword"
                        },
                        new
                        {
                            Id = 135,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/25/18/18/book-1769625_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 25,
                            MinAttackPower = 3,
                            MinHealth = 10,
                            Name = "Possessed Tome"
                        },
                        new
                        {
                            Id = 136,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/03/09/02/12/eyes-4043559_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 77,
                            MinAttackPower = 2,
                            MinHealth = 62,
                            Name = "Primal Forest Elemental"
                        },
                        new
                        {
                            Id = 137,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/01/22/12/19/travel-3098815_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 77,
                            MinAttackPower = 2,
                            MinHealth = 62,
                            Name = "Primal Light Elemental"
                        },
                        new
                        {
                            Id = 138,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/03/30/20/06/fantasy-4091953_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 50,
                            MinAttackPower = 3,
                            MinHealth = 35,
                            Name = "Primal Shaman"
                        },
                        new
                        {
                            Id = 139,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/09/10/13/06/pterosaur-2735500_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 47,
                            MinAttackPower = 3,
                            MinHealth = 32,
                            Name = "Pterosaur"
                        },
                        new
                        {
                            Id = 140,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/09/13/21/29/fantasy-2747066_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 100,
                            MinAttackPower = 6,
                            MinHealth = 95,
                            Name = "Quintessence Dragon"
                        },
                        new
                        {
                            Id = 141,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/06/25/19/47/hare-3497805_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 12,
                            MinAttackPower = 2,
                            MinHealth = 2,
                            Name = "Rabbit Spirit"
                        },
                        new
                        {
                            Id = 142,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/04/02/10/55/boar-304954_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 27,
                            MinAttackPower = 3,
                            MinHealth = 12,
                            Name = "Rabid Boar"
                        },
                        new
                        {
                            Id = 143,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/11/15/18/14/grizzlies-210996_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 32,
                            MinAttackPower = 6,
                            MinHealth = 17,
                            Name = "Rabid Cave Bear"
                        },
                        new
                        {
                            Id = 144,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/17/15/58/mammal-3024471_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 17,
                            MinAttackPower = 3,
                            MinHealth = 2,
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 145,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/09/10/13/degu-3303715_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 6,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Rat"
                        },
                        new
                        {
                            Id = 146,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Bryce_Canyon_National_Park%2C_United_States_%28Unsplash_T5Ye7puWZxo%29.jpg/640px-Bryce_Canyon_National_Park%2C_United_States_%28Unsplash_T5Ye7puWZxo%29.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 9,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Raven"
                        },
                        new
                        {
                            Id = 147,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/06/14/14/dragon-1957809_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 68,
                            MinAttackPower = 6,
                            MinHealth = 53,
                            Name = "Reanimated Dragon"
                        },
                        new
                        {
                            Id = 148,
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/04/12/14/03/skeleton-30160_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 26,
                            MinAttackPower = 2,
                            MinHealth = 11,
                            Name = "Reanimated Skeleton"
                        },
                        new
                        {
                            Id = 149,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/10/27/14/28/face-201442_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 46,
                            MinAttackPower = 3,
                            MinHealth = 31,
                            Name = "Reanimated Statue"
                        },
                        new
                        {
                            Id = 150,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/02/28/03/02/sculpture-3187129_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 42,
                            MinAttackPower = 3,
                            MinHealth = 27,
                            Name = "Reanimated Totemic Guardian"
                        },
                        new
                        {
                            Id = 151,
                            ImageUrl = "https://i.imgur.com/KN0FcNT.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 59,
                            MinAttackPower = 6,
                            MinHealth = 44,
                            Name = "Red Dragon"
                        },
                        new
                        {
                            Id = 152,
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/02/28/00/49/squirrel-17854_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 11,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Red Squirrel"
                        },
                        new
                        {
                            Id = 153,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/03/30/01/04/ghosts-2186959_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 33,
                            MinAttackPower = 2,
                            MinHealth = 18,
                            Name = "Restless Ghost"
                        },
                        new
                        {
                            Id = 154,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/05/11/15/03/spirit-2304469_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 42,
                            MinAttackPower = 2,
                            MinHealth = 27,
                            Name = "Restless Spirit"
                        },
                        new
                        {
                            Id = 155,
                            ImageUrl = "https://i.imgur.com/uL6L5Qj.png",
                            MaxAttackPower = 9,
                            MaxHealth = 16,
                            MinAttackPower = 2,
                            MinHealth = 1,
                            Name = "Rotting Slime"
                        },
                        new
                        {
                            Id = 156,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/12/30/11/17/dragon-1940366_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 59,
                            MinAttackPower = 6,
                            MinHealth = 44,
                            Name = "Ruby Dragon"
                        },
                        new
                        {
                            Id = 157,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/05/07/13/49/tiger-2292496_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 28,
                            MinAttackPower = 3,
                            MinHealth = 13,
                            Name = "Sabre Cat"
                        },
                        new
                        {
                            Id = 158,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/9c/Scale-adult-preview.png",
                            MaxAttackPower = 13,
                            MaxHealth = 65,
                            MinAttackPower = 6,
                            MinHealth = 50,
                            Name = "Sandskin Wyvern"
                        },
                        new
                        {
                            Id = 159,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/22/21/44/mask-1409287_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 27,
                            MinAttackPower = 3,
                            MinHealth = 12,
                            Name = "Satyr"
                        },
                        new
                        {
                            Id = 160,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/31/21/17/faun-2027325_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 25,
                            MinAttackPower = 3,
                            MinHealth = 10,
                            Name = "Satyr Bard"
                        },
                        new
                        {
                            Id = 161,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/02/21/13/11/hells-spirits-644224_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 42,
                            MinAttackPower = 3,
                            MinHealth = 27,
                            Name = "Satyr Lord"
                        },
                        new
                        {
                            Id = 162,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/22/21/44/mask-1409287_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 27,
                            MinAttackPower = 3,
                            MinHealth = 12,
                            Name = "Satyr Spellcaster"
                        },
                        new
                        {
                            Id = 163,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/03/03/22/27/fantasy-4033001_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 66,
                            MinAttackPower = 6,
                            MinHealth = 51,
                            Name = "Sea Dragon"
                        },
                        new
                        {
                            Id = 164,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/05/13/14/03/sea-gull-765490_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 11,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Seagull"
                        },
                        new
                        {
                            Id = 165,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/03/17/04/dragon-1949993_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 62,
                            MinAttackPower = 6,
                            MinHealth = 47,
                            Name = "Silver Wyrm"
                        },
                        new
                        {
                            Id = 166,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/09/25/19/23/mermaid-2786382_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 11,
                            MinAttackPower = 3,
                            MinHealth = 1,
                            Name = "Siren"
                        },
                        new
                        {
                            Id = 167,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/23/17/02/fantasy-2881646_960_720.jpg",
                            MaxAttackPower = 11,
                            MaxHealth = 21,
                            MinAttackPower = 4,
                            MinHealth = 6,
                            Name = "Skeleton Berserker"
                        },
                        new
                        {
                            Id = 168,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/05/24/20/51/skull-782385_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 47,
                            MinAttackPower = 2,
                            MinHealth = 32,
                            Name = "Skeleton Captain"
                        },
                        new
                        {
                            Id = 169,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/05/01/20/45/death-head-2276610_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 20,
                            MinAttackPower = 2,
                            MinHealth = 5,
                            Name = "Skeleton Troop Leader"
                        },
                        new
                        {
                            Id = 170,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/02/18/19/02/halloween-4005104_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 38,
                            MinAttackPower = 2,
                            MinHealth = 23,
                            Name = "Skeleton Trooper"
                        },
                        new
                        {
                            Id = 171,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/02/17/22/25/skull-3161081_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 46,
                            MinAttackPower = 2,
                            MinHealth = 31,
                            Name = "Skull Spirit"
                        },
                        new
                        {
                            Id = 172,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/12/14/54/slime-148995_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 9,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Slime"
                        },
                        new
                        {
                            Id = 173,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/11/23/21/22/green-tree-python-543243_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 6,
                            MinAttackPower = 2,
                            MinHealth = 0,
                            Name = "Snake"
                        },
                        new
                        {
                            Id = 174,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/19/18/43/fantasy-3028475_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 36,
                            MinAttackPower = 3,
                            MinHealth = 21,
                            Name = "Spectral Kingfisher"
                        },
                        new
                        {
                            Id = 175,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/08/17/24/butterfly-2049567_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 22,
                            MinAttackPower = 2,
                            MinHealth = 7,
                            Name = "Spectral Spirit"
                        },
                        new
                        {
                            Id = 176,
                            ImageUrl = "https://live.staticflickr.com/2814/34070170805_aa8bb0fb74_b.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 35,
                            MinAttackPower = 3,
                            MinHealth = 20,
                            Name = "Spriggan"
                        },
                        new
                        {
                            Id = 177,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/12/04/10/01/animal-3855236_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 17,
                            MinAttackPower = 3,
                            MinHealth = 2,
                            Name = "Striped Kestrel"
                        },
                        new
                        {
                            Id = 178,
                            ImageUrl = "https://dibujando.net/files/fs/p/c/900x1000/2016/297/SuccubusnInprnt_290935.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 24,
                            MinAttackPower = 3,
                            MinHealth = 9,
                            Name = "Succubus"
                        },
                        new
                        {
                            Id = 179,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/05/01/09/50/swan-4170400_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 19,
                            MinAttackPower = 3,
                            MinHealth = 4,
                            Name = "Swan"
                        },
                        new
                        {
                            Id = 180,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/01/10/19/creature-2029421_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 10,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Sylph"
                        },
                        new
                        {
                            Id = 181,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/01/15/11/08/unicorn-1981219_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 35,
                            MinAttackPower = 3,
                            MinHealth = 20,
                            Name = "Sylvan Unicorn"
                        },
                        new
                        {
                            Id = 182,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/02/23/20/31/dove-1218474_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 11,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Tame Dove"
                        },
                        new
                        {
                            Id = 183,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/04/24/10/05/monster-2255973_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 66,
                            MinAttackPower = 6,
                            MinHealth = 51,
                            Name = "Three-Headed Hydra"
                        },
                        new
                        {
                            Id = 184,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/03/26/20/49/tiger-3264048_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 18,
                            MinAttackPower = 6,
                            MinHealth = 3,
                            Name = "Tiger"
                        },
                        new
                        {
                            Id = 185,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/25/18/18/book-1769625_960_720.png",
                            MaxAttackPower = 9,
                            MaxHealth = 46,
                            MinAttackPower = 2,
                            MinHealth = 31,
                            Name = "Totem Spirit"
                        },
                        new
                        {
                            Id = 186,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/05/19/07/52/fun-773222_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 33,
                            MinAttackPower = 3,
                            MinHealth = 18,
                            Name = "Treant"
                        },
                        new
                        {
                            Id = 187,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/06/09/21/02/tree-2388245_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 34,
                            MinAttackPower = 0,
                            MinHealth = 19,
                            Name = "Tree Spirit"
                        },
                        new
                        {
                            Id = 188,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/12/18/41/faun-153712_960_720.png",
                            MaxAttackPower = 10,
                            MaxHealth = 21,
                            MinAttackPower = 3,
                            MinHealth = 6,
                            Name = "Trickster Faun"
                        },
                        new
                        {
                            Id = 189,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/12/13/13/33/log-1091115_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 36,
                            MinAttackPower = 0,
                            MinHealth = 21,
                            Name = "Trickster Tree Spirit"
                        },
                        new
                        {
                            Id = 190,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/17/20/15/troll-3328599_960_720.png",
                            MaxAttackPower = 15,
                            MaxHealth = 22,
                            MinAttackPower = 8,
                            MinHealth = 7,
                            Name = "Troll Berserker"
                        },
                        new
                        {
                            Id = 191,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/18/17/26/say-gestalt-3331025_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 37,
                            MinAttackPower = 6,
                            MinHealth = 22,
                            Name = "Troll Captain"
                        },
                        new
                        {
                            Id = 192,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/18/20/46/troll-3331579_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 20,
                            MinAttackPower = 6,
                            MinHealth = 5,
                            Name = "Troll Guard"
                        },
                        new
                        {
                            Id = 193,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/17/20/11/troll-3328570_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 17,
                            MinAttackPower = 6,
                            MinHealth = 2,
                            Name = "Troll Slave"
                        },
                        new
                        {
                            Id = 194,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/09/23/14/46/yellowstone-953835_960_720.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 46,
                            MinAttackPower = 2,
                            MinHealth = 31,
                            Name = "Vapor Spirit"
                        },
                        new
                        {
                            Id = 195,
                            ImageUrl = "https://i.imgur.com/oTi3K3q.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 80,
                            MinAttackPower = 3,
                            MinHealth = 65,
                            Name = "Viridian Amphithere"
                        },
                        new
                        {
                            Id = 196,
                            ImageUrl = "http://pngimg.com/uploads/demon/demon_PNG24.png",
                            MaxAttackPower = 13,
                            MaxHealth = 35,
                            MinAttackPower = 6,
                            MinHealth = 20,
                            Name = "Voidspawn Demon"
                        },
                        new
                        {
                            Id = 197,
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/07/13/13/49/demon-161607_960_720.png",
                            MaxAttackPower = 13,
                            MaxHealth = 20,
                            MinAttackPower = 6,
                            MinHealth = 5,
                            Name = "Voidwalker Demon"
                        },
                        new
                        {
                            Id = 198,
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/26/14/50/animals-3352109_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 6,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Weasel"
                        },
                        new
                        {
                            Id = 199,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/07/16/20/39/dove-1522656_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 11,
                            MinAttackPower = 3,
                            MinHealth = 0,
                            Name = "Wild Dove"
                        },
                        new
                        {
                            Id = 200,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/10/31/07/49/horses-2904536_960_720.jpg",
                            MaxAttackPower = 13,
                            MaxHealth = 18,
                            MinAttackPower = 6,
                            MinHealth = 3,
                            Name = "Wild Stallion"
                        },
                        new
                        {
                            Id = 201,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/05/18/16/58/abstract-772508_960_720.jpg",
                            MaxAttackPower = 10,
                            MaxHealth = 56,
                            MinAttackPower = 3,
                            MinHealth = 41,
                            Name = "Wizard"
                        },
                        new
                        {
                            Id = 202,
                            ImageUrl = "https://i.stack.imgur.com/S21a4.jpg",
                            MaxAttackPower = 9,
                            MaxHealth = 20,
                            MinAttackPower = 2,
                            MinHealth = 5,
                            Name = "Wood Spider"
                        },
                        new
                        {
                            Id = 203,
                            ImageUrl = "http://pngimg.com/uploads/demon/demon_PNG20.png",
                            MaxAttackPower = 13,
                            MaxHealth = 30,
                            MinAttackPower = 6,
                            MinHealth = 15,
                            Name = "Wormwing Demon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
